name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    permissions:
      id-token: write # This permission is needed to interact with GitHub's OIDC Token endpoint.
      contents: write # This permission is needed to interact with GitHub's OIDC Token endpoint & upload release.
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Parse tag name
      shell: bash
      run: |
         REF_NAME=${{ github.ref_name }}
         VERSION=${REF_NAME#v}
         SEMVER_REGEX='^((0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*))(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$'
         echo "VERSION=$VERSION" >> $GITHUB_ENV
         if [[ $VERSION =~ $SEMVER_REGEX ]]
         then
           echo "MAIN_VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
           echo "PRE_RELEASE_VERSION=${BASH_REMATCH[6]}" >> $GITHUB_ENV
         else
           echo "$VERSION doesn't match"
         fi
    - name: Publish
      run: dotnet publish ./src/Joba.IBM.RPA.Cli/Joba.IBM.RPA.Cli.csproj -c Release -f net7.0 -r win-x64 -p:PublishSingleFile=true -p:VersionPrefix=${MAIN_VERSION} -p:VersionSufix=${PRE_RELEASE_VERSION} -o ./publish --self-contained
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::578599518237:role/Github-ibm-rpa-cli-Role
        role-session-name: MySessionName
        aws-region: us-east-1
    - name: Upload to AWS S3
      run: |
        aws s3api put-object --bucket joba-ibm-rpa-cli --key ${{env.VERSION}}/
        aws s3 cp './publish/rpa.exe' s3://joba-ibm-rpa-cli/releases/${{env.VERSION}}/
    - name: Github release
      shell: pwsh
      run: |
        if ( $null -eq "${{env.PRE_RELEASE_VERSION}}" -or "${{env.PRE_RELEASE_VERSION}}" -eq '' ) {
          gh release create ${{ github.ref_name }} './publish/rpa.exe#rpa cli' --title "Release ${{env.VERSION}}" --verify-tag --generate-notes
        }
        else {
          gh release create ${{ github.ref_name }} './publish/rpa.exe#rpa cli' --title "Release ${{env.VERSION}}" --verify-tag --prerelease --generate-notes
        }
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}