name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Parse tag name
      shell: bash
      run: |
         REF_NAME=${{ github.ref_name }}
         VERSION=${REF_NAME#v}
         SEMVER_REGEX='^((0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*))(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$'
         echo "VERSION=$VERSION" >> $GITHUB_ENV
         if [[ $VERSION =~ $SEMVER_REGEX ]]
         then
           echo "MAIN_VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
           echo "PRE_RELEASE_VERSION=${BASH_REMATCH[6]}" >> $GITHUB_ENV
         else
           echo "$VERSION doesn't match"
         fi
    - name: Build
      run: dotnet publish ./src/Joba.IBM.RPA.Cli/Joba.IBM.RPA.Cli.csproj -c Release -f net7.0 -r win-x64 -p:PublishSingleFile=true -p:VersionPrefix=${MAIN_VERSION} -p:VersionSufix=${PRE_RELEASE_VERSION} -o ./publish --self-contained
    - name: e2e tests
      run: dotnet test ./src/Tests/Joba.IBM.RPA.Cli.Tests --filter "Category=e2e" --verbosity normal
      env:
        RPA_EXECUTABLE_PATH: ${{github.workspace}}/publish/rpa.exe
        E2E_SOURCE_URL: ${{ vars.E2E_SOURCE_URL }}
        E2E_SOURCE_REGION: ${{ vars.E2E_SOURCE_REGION }}
        E2E_SOURCE_TENANT: ${{ vars.E2E_SOURCE_TENANT }}
        E2E_SOURCE_USERNAME: ${{ vars.E2E_SOURCE_USERNAME }}
        RPA_SECRET_source: ${{ secrets.DEV_TENANT_PASSWORD }}
        E2E_TARGET_URL: ${{ vars.E2E_TARGET_URL }}
        E2E_TARGET_REGION: ${{ vars.E2E_TARGET_REGION }}
        E2E_TARGET_TENANT: ${{ vars.E2E_TARGET_TENANT }}
        E2E_TARGET_USERNAME: ${{ vars.E2E_TARGET_USERNAME }}
        RPA_SECRET_target: ${{ secrets.QA_TENANT_PASSWORD }}
        E2E_PACKAGE_URL: ${{ vars.E2E_PACKAGE_URL }}
        E2E_PACKAGE_REGION: ${{ vars.E2E_PACKAGE_REGION }}
        E2E_PACKAGE_TENANT: ${{ vars.E2E_PACKAGE_TENANT }}
        E2E_PACKAGE_USERNAME: ${{ vars.E2E_PACKAGE_USERNAME }}
        RPA_SECRET_package: ${{ secrets.JOBA_TENANT_PASSWORD }}
    - name: Github release
      shell: pwsh
      run: |
        if ( $null -eq "${{env.PRE_RELEASE_VERSION}}" -or "${{env.PRE_RELEASE_VERSION}}" -eq '' ) {
          gh release create ${{ github.ref_name }} './publish/rpa.exe#rpa cli' --title "Release ${{env.VERSION}}" --verify-tag --generate-notes
        }
        else {
          gh release create ${{ github.ref_name }} './publish/rpa.exe#rpa cli' --title "Release ${{env.VERSION}}" --verify-tag --prerelease --generate-notes
        }
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}